apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: gateway-container
          image: europe-central2-docker.pkg.dev/lithe-aileron-486115-t3/microservices-repo/api-gateway:v11
          ports:
            - containerPort: 1000
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
          env:
            - name: NODE_SERVICE_URL
              value: "http://node-service-svc:7777"
            - name: SONGS_SERVICE_URL
              value: "http://songs-service-svc:8088"
            - name: CONSUL_ENABLED
              value: "false"
            - name: GOOGLE_REDIRECT_URI
              value: "http://34.116.141.50.nip.io/login/oauth2/code/google"
            - name: FRONTEND_URL
              value: "http://34.116.141.50.nip.io"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-external-svc
spec:
  type: LoadBalancer
  loadBalancerIP: "34.116.141.50"
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1000
